# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_category', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='information',
        ),
        migrations.AddField(
            model_name='animal_category',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstWeb.Animal_type'),
        ),
    ]
